### ISSUE TITLE
Error with custom repos command when has a invalid repo path.

### ISSUE THREAD

**Issue by zlj-zz** [zlj-zz/pigit#47]
```
:: git fetch

Traceback (most recent call last):
  File "/opt/homebrew/bin/pigit", line 33, in <module>
    sys.exit(load_entry_point('pigit==1.7.0.dev0', 'console_scripts', 'pigit')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pigit-1.7.0.dev0-py3.11.egg/pigit/comm/func.py", line 19, in wrap
    res = fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pigit-1.7.0.dev0-py3.11.egg/pigit/entry.py", line 309, in main
    pigit()
  File "/opt/homebrew/lib/python3.11/site-packages/pigit-1.7.0.dev0-py3.11.egg/pigit/cmdparse/parser.py", line 207, in __call__
    self.main(args, **kwds)
  File "/opt/homebrew/lib/python3.11/site-packages/pigit-1.7.0.dev0-py3.11.egg/pigit/cmdparse/parser.py", line 202, in main
    known_args.sub_callback(known_args, unknown)
  File "/opt/homebrew/lib/python3.11/site-packages/pigit-1.7.0.dev0-py3.11.egg/pigit/comm/func.py", line 63, in wrap
    return fn(*args, **final_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pigit-1.7.0.dev0-py3.11.egg/pigit/entry.py", line 281, in <lambda>
    lambda args, _, cmd: repo_handler.process_repos_option(args.repos, cmd),
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pigit-1.7.0.dev0-py3.11.egg/pigit/git/repo.py", line 836, in process_repos_option
    return self.executor.exec_async(*cmds, orders=orders, flags=WAITING)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pigit-1.7.0.dev0-py3.11.egg/pigit/comm/executor.py", line 237, in exec_async
    return asyncio.run(_async_tasks(tasks))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pigit-1.7.0.dev0-py3.11.egg/pigit/comm/executor.py", line 225, in _async_tasks
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pigit-1.7.0.dev0-py3.11.egg/pigit/comm/executor.py", line 201, in _async_cmd
    proc = await asyncio.create_subprocess_exec(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/subprocess.py", line 221, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1694, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/unix_events.py", line 207, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/unix_events.py", line 818, in _start
    self._proc = subprocess.Popen(
                 ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/lijunzhang/Projects/zachary/CloudLocalTestTool'
```

**Comment by zlj-zz** [comment]
Finish
